name: CI

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  prepare:
      name: Prepare
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - uses: ./.github/actions/yarn-setup
          with:
            node-version: ${{ env.NODE_VERSION }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'

      - name: Generate Graphql Types
        shell: bash
        run: ./bin/graphql/generate.sh

      - run: yarn affected:build --parallel --base=${{ env.NX_BASE }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'

      - run: yarn affected:lint --parallel --base=${{ env.NX_BASE }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'

      - run: yarn affected:test --parallel --base=${{ env.NX_BASE }}

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
